# Generated by Django 4.2.7 on 2024-12-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
